name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to HF (Meglévő Space-re)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # A meglévő repód neve a Hugging Face-en:
          git push --force https://pityumajsaii-cell:$HF_TOKEN@huggingface.co/spaces/pityumajsaii-cell/titanium_v5 main
